### ISSUE TITLE
Find a better name for the package

### ISSUE THREAD

**Issue by dirkschumacher** [R4EPI/sitrep#11]
There is the EpiReport already published by ECDC. Ideas welcome :)

**Comment by dirkschumacher** [comment]
I like sitrep. Anyone else? @zkamvar @thibautjombart

**Comment by zkamvar** [comment]
I think that’s the one that will make the most sense to epis. 👍🏽

**Comment by thibautjombart** [comment]
I like *sitrep* ; otherwise, alternatives:

- *sitrep++*
- *mysitrepsbetterthanurs*
- *sitrepyeah*
- *sitrepyeahhmyeah*
- *sprite*

**Comment by dirkschumacher** [comment]
Thanks @zkamvar and @thibautjombart . I would suggest we go for sitrep then. What does @epiamsterdam say?
