### ISSUE TITLE
Hackathon Issues

### ISSUE THREAD

**Issue by aspina7** [R4EPI/sitrep#136]
Morning @zkamvar - Think probably the easiest thing to do is to start a bullet list, then for each bullet sit it out so that it contains the name of person who raised issue in brackets, then the disease template (cholera, ajs, measles, meningitis) they were using, followed by a dash and the codechunk (or general) and then the error or issue. followed by solution in double brackets, at the end of it once fixed. e.g.: 

* [x] [Annick] [Cholera - general] Didnt know how to turn computer on [[Solution: pushed the button]]
* [x] [Annick] [Cholera - read_dhis_data] Didnt know what an excel file was [[Solution: googled it]]
* [x] [Elburg] [Sitrep - general] Error when updating packages based on wiki - Error: failed to install 'sitrep' from github: (converted from warning) cannot remove prior installation of package 'rlang' [[Solution: Turn on and off]]
* [x] [Zhian] [Outbreaks - gen_data] simulated data: sometimes it will generate an explicit missing variable for gender and other times not
* [x] [Kate] [Sitrep - general] we deleted the general outbreak template from sitrep. Kate gets an error that cannot read yaml because doesnt exist. Cannot open file 'templates/outbreak/template.yaml': No such file or directory

**Comment by zkamvar** [comment]
[Kate][Sitrep - xl.read.file] There is an issue with protected sheets:

> linelist_raw <- xl.read.file("hack_data/bituvis-cholera.xlsx",
                         xl.sheet = "xxxxx",
                         password = askpass::askpass("xxxxx"))
Error in top_left_corner["CurrentRegion"] : You cannot use this command on a protected sheet. To use this command, you must first unprotect the sheet (Review tab, Changes group, Unprotect Sheet button). You may be prompted for a password. (Microsoft Excel) <checkErrorInfo> 80020009

**Comment by nsbatra** [comment]
[Kate] [Sitrep - load packages] Put commented lines with commands for installing optional packages like askpass, excel.link, etc.

**Comment by aspina7** [comment]
[Kate] [Training] walk people through commenting / uncommenting lines

**Comment by aspina7** [comment]
[Kate] [cleaning] clean_colnames from epitrix will remove a column called "#"

**Comment by zkamvar** [comment]
> [Kate] [cleaning] clean_colnames from epitrix will remove a column called "#"

This is solved by updating epitrix and including `protect = "#"`

**Comment by nsbatra** [comment]
[Neale] [Sitrep - read data] Pasting filepaths to rio::import might give an error which required the user to change the slashes from \ to / . (this happened to me)

**Comment by zkamvar** [comment]
[Kate][cholera cleaning] There does not appear to be an ID field in the Cholera dictionary

**Comment by zkamvar** [comment]
General: add instructions for setting up RStudio project to link data and project

**Comment by zkamvar** [comment]
[Kate] Renaming variables without any order is *exquisitely painful*

**Comment by zkamvar** [comment]
[Maria][ajs_outbreak save_cleaned_data]: writexl needs to be installed first

**Comment by zkamvar** [comment]
[Elburg][AJS 313] this is missing a parens: `# linelist_cleaned <- select(linelist_cleaned, c(1:3, "age_years", "sex")`

**Comment by aspina7** [comment]
[Kate] [Cholera  clean_dates]  Error in charToDate(x) : character string is not in a standard unambiguous format - despite all in format %d %B %Y

**Comment by nsbatra** [comment]
[Neale][Cholera - read non-DHIS data] In the commented instructions line 245, update description of data dictionary column names from "Code" to "option_code" and "Name" to "option_name"

**Comment by zkamvar** [comment]
> [Kate] [Cholera clean_dates] Error in charToDate(x) : character string is not in a standard unambiguous format - despite all in format %d %B %Y

Note: this needed to be in %d-%b-%y

**Comment by zkamvar** [comment]
[Kate][Cholera]: in cholera for obs_days, should it use date_of_admission instead of date_of_consultation_admission?

**Comment by aspina7** [comment]
[kate] [general] people dont seem to be reading comments and are then confused about whats happening/where they are. 
Hopefully training material and the wiki (outlining the structure and content of scripts will help...)

**Comment by aspina7** [comment]
[Annick] [training] Note for teaching: the population data setcion isnt really clear - we need to make something that people understand and also an instruction on how to format the population data in the best way.

**Comment by aspina7** [comment]
[Elburg] [variable_naming] for non DHIS2 data, need to clarify how much needs to fit (variables!) in order for it to run. 
"I think I missed somehting, do I need to rename all the variables so that they match the dictionary?"

**Comment by aspina7** [comment]
[kate] [clean variables - factors] case_when creates a character variable, make sure to say as much in the script comments. Currently says will recode to a factor. Then again we need to re-do all the factor stuff anyway.

**Comment by nsbatra** [comment]
[Neale] [Sitrep general] Just noting that my non-DHIS 2 dataset has separate columns for Day (numeric) and for Month (text). A user would need to clean/paste them for use in these templates. This may be something not worth addressing structurally in linelist or sitrep, but let's chat about how likely this is and whether it's worth mentioning somewhere in the instructions.

**Comment by zkamvar** [comment]
> [Neale] [Sitrep general] Just noting that my non-DHIS 2 dataset has separate columns for Day (numeric) and for Month (text). A user would need to clean/paste them for use in these templates. This may **not** be something worth addressing structurally in linelist or sitrep, but let's chat about how likely this is and whether it's worth mentioning somewhere in the commented instructions.

This is included in the FAQ: https://github.com/R4EPI/sitrep/wiki/4)-FAQ#i-have-a-date-column-and-a-time-column-how-do-i-combine-the-two

**Comment by aspina7** [comment]
[Kate] [cholera - dict] msf dict category options show up wrong e.g. sex shows options for pregnancy trimester

**Comment by nsbatra** [comment]
[Maria] [sitrep - read data] Let's consider putting the code for generating the dummy dataset _before_ the code for reading in your own dataset, so that if the user forgets to comment/delete the gen_data line the script will still use the data they have imported.

**Comment by zkamvar** [comment]
[Kate] Move reporting week to preamble

[Annick]: use knitr params

**Comment by zkamvar** [comment]
[Kate]: Not clear that sex/gender needs to be a factor

**Comment by aspina7** [comment]
[kate] [data cleaning] doesnt like that you are filtering and then not assigning to a new new data set, i.e. have linelist_raw, linelist_clean and then when filtering assign to e.g. linelist_analysis.
All came about because of mistake when passing arguments to filter command which left 0 cases in dataset. New people would justifiably freak out!
Maybe another thing for training??

**Comment by aspina7** [comment]
[Alanah] [recode_factors] "" = NA_character_ when actually the missings where " ". Error returns zero length variable... not super intuitive to understand whats wrong...

**Comment by zkamvar** [comment]
[Elburg] [general]: One of my parting thoughts is idd when you give examples to keep them in line with the rest of the script. I followed the renaming example of sex -> gender and now have to change sex to gender every where in the scripts

**Comment by zkamvar** [comment]
[Kate][General]: `rio::import()` converts files to UTF-8, but `readr::read_csv()` does not, which causes problems for cleaning functions that expect utf8

**Comment by aspina7** [comment]
[Ettiene] [Install] Admin rights issue, cant install package - also cant change .rprofile to change where packages are written to.

**Comment by aspina7** [comment]
[Isidro] [installing] Add a note to restart R before installing new packages

**Comment by aspina7** [comment]
[Anna] [renaming variables] easier way to list out all the variable names in datasets rather than clicking back and forth.

**Comment by aspina7** [comment]
[Ettiene] [reading_data] importing Excel data from a OCG linelist, the data do not iatart n the first row first column, there are in a specific range, 
Add a walkthrough of how to read in specific cell range.

**Comment by aspina7** [comment]
[Pat] [reading_dhis_excel_data] wall of text dense. Considering breaking up in to smaller chunks.

**Comment by aspina7** [comment]
[Anna] [renaming variables] measles reading non-dhis2 data, the renmaing examples dont match the dictionary so is confusing.

**Comment by aspina7** [comment]
[Kate/Isidro] [ population data] considering adding the option to also type in population counts (not props) e.g. for village wouldnt necessarily have proportions. But still useful to have proportions for age group breakdowns. (and to show how to read in counts from an excel)

**Comment by aspina7** [comment]
[Kate] fmt_counts in cholera treatment plans if there are zero counts in there then returns character(0) - unsure wether fmt_count will fix this automatically and output 0 (0%) in the word doc. 
May need to add to fmt_count that returns 0 if as.character comes back.

**Comment by aspina7** [comment]
[kate] [cholera obs_days] Cholera -- Median, min, and max days_obs need an na.rm = T added

**Comment by aspina7** [comment]
[Kate] [cholera CFR] - add an option to turn off CIs in cfr calculation - for eg if it is a closed population and are certain that all deaths are being captured (i.e. inpatients). If making an assumption that those deaths are representative of community-wide deaths then need to have CIs.

**Comment by aspina7** [comment]
[Pat] [fixing dates] # # set unrealistic dates to NA, based on having browsed dates in the previous chunk
  linelist_cleaned <- mutate(linelist_cleaned,
                             date_of_onset < as.Date("2017-11-01") ~ NA, 
                             date_of_onset == as.Date("2081-01-01") ~ as.Date("2018-01-01"))

Getting Error: Column `date_of_onset < as.Date("2017-11-01") ~ NA` is of unsupported type quoted call
as.Date(NA) 

instead of NA?
@pat: yes

**Comment by aspina7** [comment]
[kate] [cholera Attacke rate] overall and by age group - different multiplier. Overall is by 10,000 and age group by 100,000. 
Change all to be 10,000  - double check in other templates to see if same.

**Comment by zkamvar** [comment]
[Elburg][symptoms]. There was an issue with symptoms in which Elburg had data that had various calls for yes and no. This needed to be cleaned. I've templated a small example

``` r
  library("sitrep")
  library("dplyr")
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

dat <- data.frame(
  tidy_symptoms = sample(c("Yes", "No", "Unknown"), 100, replace = TRUE, prob = c(0.3, 0.6, 0.1)),
  num_symptoms = sample(c(0, 1, NA), 100, replace = TRUE, prob = c(0.3, 0.6, 0.1)),
  mixed_symptoms = sample(c("Yes", "No", "Unknown", 1, 0), 100, replace = TRUE, prob = c(0.3, 0.6, 0.05, 0.025, 0.025))
)


NAMES <- colnames(dat)
sitrep::multi_descriptive(dat, NAMES)
#> converting numeric variable to factor
#> # A tibble: 3 x 25
#>   symptom  No_n No_prop Total_n Total_prop Unknown_n Unknown_prop Yes_n
#>   <chr>   <dbl>   <dbl>   <dbl>      <dbl>     <dbl>        <dbl> <dbl>
#> 1 tidy_s…    50    50       100        100        11           11    39
#> 2 num_sy…    NA    NA       100        100        NA           NA    NA
#> 3 mixed_…    57    57.0     100        100         6            6    35
#> # … with 17 more variables: Yes_prop <dbl>, `(0,0.2]_n` <dbl>,
#> #   `(0,0.2]_prop` <dbl>, `(0.2,0.4]_n` <dbl>, `(0.2,0.4]_prop` <dbl>,
#> #   `(0.4,0.6]_n` <dbl>, `(0.4,0.6]_prop` <dbl>, `(0.6,0.8]_n` <dbl>,
#> #   `(0.6,0.8]_prop` <dbl>, `(0.8,1]_n` <dbl>, `(0.8,1]_prop` <dbl>,
#> #   Missing_n <dbl>, Missing_prop <dbl>, `0_n` <dbl>, `0_prop` <dbl>,
#> #   `1_n` <dbl>, `1_prop` <dbl>
dat2 <- dat %>%
  mutate_at(vars(NAMES), ~case_when(
    . == "Yes" ~ "Yes",
    . == "y"   ~ "Yes",
    . == "Y"   ~ "Yes",
    . == "No"  ~ "No",
    . == "N"   ~ "No",
    . == "n"   ~ "No",
    . == 1     ~ "Yes",
    . == 0     ~ "No",
    TRUE       ~ "Unknown"
    ))
sitrep::multi_descriptive(dat2, NAMES)
#> # A tibble: 3 x 9
#>   symptom  No_n No_prop Total_n Total_prop Unknown_n Unknown_prop Yes_n
#>   <chr>   <dbl>   <dbl>   <dbl>      <dbl>     <dbl>        <dbl> <dbl>
#> 1 tidy_s…    50    50       100        100        11           11    39
#> 2 num_sy…    22    22       100        100         6            6    72
#> 3 mixed_…    58    58.0     100        100         6            6    36
#> # … with 1 more variable: Yes_prop <dbl>
```

<sup>Created on 2019-07-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by aspina7** [comment]
[kate] [cholera mortality rate] - with zero deaths then the table comes out with deaths - and population - and CIs of NA-NA .... considering adding to function to have 0 come out rather than - and NA 

DeathsPopulationMortality (per 10,000)95%CI
      -               -               10000            (NA–NA)

**Comment by aspina7** [comment]
[Elburg] [AJS lab tests] did not have all the lab variables listed in LABS - add an explanation to comment out the ones dont have. Alternatively Zhian consider adding to multi_descriptive function to drop non existant variables and return a warning message that those variables have been ignored.

**Comment by zkamvar** [comment]
[Elburg][AJS lab tests] Same as https://github.com/R4EPI/sitrep/issues/136#issuecomment-508784556, she didn't have the expected variables and so select and rename were failing.

**Comment by aspina7** [comment]
[Kate] [loading packages] here::here package is not loaded ... but used in the spatial data section

**Comment by aspina7** [comment]
[Anna] [standardise_clean filtering] a lot of datasets will fill case_id down automatically even if nothing else is filled in yet. Show example code at the filter bit to show how to drop

**Comment by aspina7** [comment]
[Kate] [reading shapefiles] actually read_sf does need to be told .shp at the end! i thought it recognises automatically from name

**Comment by aspina7** [comment]
[kate/Annick] [maps] change colour palletes - dark for highest AR

**Comment by aspina7** [comment]
[Elburg] [epicurves] show an example of how to change the x axis labels in epicurves. Because for example with loads of data is then uuuugly.

**Comment by zkamvar** [comment]
from kate:
A weird thing -- I originally had a line list with data from 2016--now. I filtered to only include 2019. So when I am running attack rate by week, there is a piece of code that keeps all the factor levels, which mucks up my AR by week. 

```r
    # counts and cumulative counts by week
    cases <- linelist_cleaned %>%
      arrange(date_of_admission) %>%        # arrange by date of onset
      count(epiweek, .drop = FALSE) %>% # count all epiweeks and include zero counts
      mutate(cumulative = cumsum(n))    # add a cumulative sum
```

Z: I guess you need to add a new filter statement in there for epiweek    
K: Fair    
K: Similar issue with describe_admissions_by_epiweek and describe_exits_by_epiweek -- not sure how to filter there    
Z: I forget what disease template you're on?    
K: Cholera. But it's basically that i have unused factor levels in epiweek -- any easy way to drop them?
Z: Convert it to character. We added that in there so that any missing weeks would be highlighted.    
K: Can I do that in the initial creation, or needs to be in that statement only?    
Z: You can do it in the initial creation if you'd like, so you can select factor = FALSE in the epiweek creation. If you want the ability to count missing weeks, then you can use factor_aweek() after you filter your data and it will create levels that span the range of your data. 

K: follow-up, changed it to this so i could keep unused levels but only in 2019

```r
    descriptive(linelist_cleaned, "epiweek", coltotals = TRUE, rowtotals = TRUE) %>% 

      filter(grepl("2019", epiweek)) %>%

      augment_redundant("_n$" = " (n)") %>% # modify _n to (n)

      rename_redundant("prop" = "%")    %>% # rename proportions to %

      kable(digits = 2)
```

Z:is epiweek a character in your linelist or a factor? Oh, duh, you can just drop those levels with forcats::fct_drop(): https://forcats.tidyverse.org/reference/fct_drop.html
But yeah, it shouldn't matter too much. I think what you have above is good.

**Comment by pbkeating** [comment]
Making a flow chart to guide users through the templates would be helpful

**Comment by aspina7** [comment]
closing as have the cleaned hackathon to-do-list in place
