### ISSUE TITLE
Synch names for descriptive() and tabulate_survey()

### ISSUE THREAD

**Issue by zkamvar** [R4EPI/sitrep#144]
The `descriptive()` and `tabulate_survey()` functions do the exact same thing, just on either a linelist or a survey, respectively. They both calculate counts with proportions. The only difference is that tabulate_survey also reports confidence intervals with these proportions. 

There are also things like the fact that descriptive has `explicit_missing` and `tabulate_survey()` has `na.rm` ಠ_ಠ

These two need to have standardized names and arguments. Proposal:

 - [ ] change `descriptive()` to `tab_linelist()`
 - [ ] change `tabulate_survey()` to `tab_survey()`
 - [ ] change `explicit_missing` to `na.rm`
 - [ ] make sure things are cromulent

**Comment by aspina7** [comment]
tab_linelist and tab_survey

**Comment by zkamvar** [comment]
I'm going to close this to move the discussion over to #151
