### ISSUE TITLE
Add list of potential data errors

### ISSUE THREAD

**Issue by dirkschumacher** [R4EPI/sitrep#15]
Amrish please :)

**Comment by AmmerB** [comment]
**General data preparation, database shaping operations**

This includes most common practices in cleaning and shaping data bases pre-analyses
Ultimately great to have all of this in one package e.g. [Epitrix](https://www.repidemicsconsortium.org/epitrix/)

- [ ] Clean variable names (remove special characters and make everything lower case): clean_labels() in epitrix (any unresolved issues there? @thibautjombart @zkamvar 
- [ ] Clean and standardize class based on variable name and most common values in column: based on most commonly used variables and expected values (e.g. gender, age, symptom onset, date x,y, latitude/longitude, for other values maybe "ask" how to classify variable)
- [ ] Clean and standardize dates: linelist function/package @thibautjombart @zkamvar 
Amrish: highlighting expected values (e.g. American dates vs UK dates)
- [ ] Generating an easy summary table to highlight/summarize unexpected values (are out expected range, e.g. in age, or in date), to make correcting them easier: e.g a table with ID and unexpected values)
- [ ] Easy collapsing of datasets to calculate frequencies "by" / "or" e.g. to calculate prevalence by household in a linelist of individuals

Other issues: @dirkschumacher @aspina7 @zkamvar @thibautjombart

**Comment by thibautjombart** [comment]
Good thing a few of these are already covered in `linelist`. At this stage we need to distinguish what I'd call:

1. ** data standardisation**: using consistent labels and conventions, cleaning non standard characters, processing dates as such, even detecting date formats etc. 

2. ** data cleaning **: (for lack of a better work) this is what is left in terms of errors once standardisation has been done; this is a lot less straightforward, as it will need to rely on ad hoc rules; e.g. age can be only this range, different dates need to obey a given order, etc. 

1. belongs to `linelist`; 2. will be a different package, and can get very complex (like AI level complex); it is possible to come up with simple, sell contained solutions, and I believe Rich Fitz has made progress on that. I started discussing coordinating this and there will be developments on this front looking forward, but this goes beyond the scope of the current funded project. Any such cleaning should probably remain ad hoc scripts for the time being.

**Comment by aspina7** [comment]
agree - think easiest place to start is with defining a data dictionary. 
After that the number of different rules/operations will be minimal and largely predictable

**Comment by zkamvar** [comment]
I am working on the data dictionary in https://github.com/reconhub/linelist/issues/2

**Comment by aspina7** [comment]
@zkamvar  make sure you cross check with @epiamsterdam about the linelist data dictionaries she already has

**Comment by aspina7** [comment]
This has been addressed in the data cleaning section of templates which breaks it down by variable type. This can be changed to linelist package at a later date.
