### ISSUE TITLE
Date functions in templates and training materials

### ISSUE THREAD

**Issue by nsbatra** [R4EPI/sitrep#167]
Copying conversation over from Slack (9 Aug 2019):

**Neale:**
Hi all, I wanted to make sure I understand the date cleaning section of the templates (AJS copied below for reference).

There are two sections of helper code, and I have encountered issues with each that I want to make sure I understand correctly.
I plan to discuss these issues in the training text, and then taking a more manual approach for the Chad variables, walking-through steps for converting variables one-at-a-time. I think it is wise to take this manual approach in the training so the users see an example of that to reference if they get stuck. Thanks for your thoughts!

1) If your dataset *completely* matches the data dictionary, then you can use the first code bit to convert class "en masse" based on your variables' names being in DATEVARS, which comes from *all* the date variables in the data dictionary. However, I found that if your dataset does not contain _even one_ of those date variables in the data dictionary, then you get an error and none are converted:

```
Error in (function (x, ...)  : 
  object 'arrival_date_in_area_if_3m' not found
```

2) If your dataset doesn't match the data dictionary, then there is helper code to convert class "en masse" using matches() and looking for "date" or "Date" in the variable name. But in the non-standard Chad data for example, some variables would be missed because their name contains "dt" (e.g. dtdeath, which does not have a corollary in data dictionary). I also got an error from one (unspecified) variable not having a consistent format and so no changes were made (supports the approach of going one-by-one). This code is also written using as.Date() with no format specified (default is yyyy-mm-dd), so if your dates are differently formatted you'd need to add the format= argument also.

```r
# Date variables ---------------------------------
# IF YOU ARE USING THE DATA DICTIONARY USE THIS OTHERWISE UNCOMMENT LINES BELOW
# make sure all date variables are formatted as dates 
DATEVARS <- filter(linelist_dict, data_element_valuetype == "DATE") %>% 
  select(data_element_shortname) # select date vars
# change to dates 
linelist_cleaned <- linelist_cleaned %>%
  mutate_at(DATEVARS$data_element_shortname, as.Date)

# if you dont have a data dictionary you could do it this way too
 linelist_cleaned <- linelist_cleaned %>%
   mutate_at(vars(matches("date|Date")), as.Date)
```

**Zhian**:
You might want to take a look at Kate's housekeeping branch: https://github.com/R4EPI/sitrep/pull/166
There are several points to unpack here, so I'll tackle what I can piece by piece:
regarding the use of as.Date(): Kate changed this to use linelist::guess_dates(), which is a bit more flexible with format (albiet a bit slower): https://github.com/R4EPI/sitrep/pull/166/commits/93344dfdc752fb9686a9a71c6de7e873fddd432e#diff-9c004dd788c1405ba45ae444e6fc974aR566

Regarding DATEVARS matching exactly:
I think we can add an extra filtering step in generating the DATEVARS:

```r
DATEVARS <- filter(linelist_dict, data_element_valuetype == "DATE") %>%
  filter(data_element_shortname %in% names(linelist_clean)) %>% # NEW BIT
  select(data_element_shortname) # ZNK note: I think this should be changed to PULL
```
Regarding trying to match non-standard data.... oof
You've highlighted a VERY good point
the problem is that trying to find variables in non-standard data is an absolute nightmare.

**Neale:**
Thanks Zhian - I think the new filter line added to the DATEVARS chunk is good.
Non-standard is proving difficult, but that's part of the game I guess, and could be common for a while.
Regarding the move to guess_dates() - should I then shift all the training material (even the R Basics section on dates) from as.Date to guess_dates? Or talk about them both? If the epis google or read the other Intro R reference links they will probably still mostly encounter as.Date.

**Zhian:**
Dates are a huge pain in the ass
There are several ways to parse dates in R and all of them have flaws
as.Date --- base R and absolute madness to try and do mixed formats
lubridate::parse_date_time() works most of the time, but can get dates fantastically wrong if you aren't careful
anytime::anytime doesn't really like date strings that are slightly messy
parsedate::parse_date() works pretty well, but will fail in 18 years (you can ask me how later)
linelist::guess_date() uses lubridate under the hood, can be slow, and is slightly insane, but it tries to pick up where the others leave off
Also, I think this is a significant enough conversation to stick on github because slack likes to delete things

**Comment by kdoyle514** [comment]
> Regarding the move to guess_dates() - should I then shift all the training material (even the R Basics section on dates) from as.Date to guess_dates? Or talk about them both? If the epis google or read the other Intro R reference links they will probably still mostly encounter as.Date.

I think talk about them both. Since as.Date is so common, it's worth having in there. I often use it when I know how the dates are formatted already. But since we get insane data in real life, and in MSF, that's why we use guess_dates and its slightly insane insides. I mean, you will probably put that more elegantly. But yes.

**Comment by aspina7** [comment]
agree with kate - lets stick with guess_dates in templates and then in the training walk people through as.Date, date formats and the origin option for reading form excel.

**Comment by nsbatra** [comment]
Closing as resolved.
