### ISSUE TITLE
Attack rate at maximum if data are missing

### ISSUE THREAD

**Issue by zkamvar** [R4EPI/sitrep#171]
``` r
sitrep::attack_rate(NA, NA)
#>   cases population  ar lower upper
#> 1    NA         NA 100    NA    NA
```

<sup>Created on 2019-08-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This is likely a bug in the internal `proportion()` function.

**Comment by nsbatra** [comment]
Also - 
If there are cases but no population, attack_rate currently produces NA for both. It should be the case count and NA for population. 

```r
attack_rate(10, NA)
  cases population  ar lower upper
    NA         NA 100    NA    NA

```

**Comment by nsbatra** [comment]
It makes the bar charts of attack rates pretty interesting...!  

![image](https://user-images.githubusercontent.com/52152191/63503522-eaea2a80-c4cf-11e9-968c-ed6a4b685cd5.png)

**Comment by nsbatra** [comment]
note: mortality_rate() appears to have the same bugs. 
Interestingly, groups that have deaths do appear as rows in the table (those without deaths do not), but the deaths column in the table is NA if the population column in the table is NA.

**Comment by zkamvar** [comment]
> note: mortality_rate() appears to have the same bugs.

All of the _rate functions will have this bug. I will fix it.
