### ISSUE TITLE
Nice-to-haves

### ISSUE THREAD

**Issue by aspina7** [R4EPI/sitrep#185]
[sitrep::msf_dict] consider a simpler way to have an overview of vriable value options - clicking in to each one defeats the purpose of reading in a dictionary (should be able to have dictionary open and look things up while recoding). Also double check that the value options that are produced are correct (though this seems to be have been a one-time issue. [comment](https://github.com/R4EPI/sitrep/issues/136#issuecomment-508496907)

**Comment by aspina7** [comment]
[Sitrep - renaming vars] making non-DHIS datasets fit is very painful. Add explanation of sitrep::msf_dict_rename_helper()  - also add to this function to say whether those variables are OPTIONAL or NECESSARY for the template to run. Consider also changing variables to alphabetic order. ~~Consider  integrating the [codebook](https://rubenarslan.github.io/codebook/) package~~
 [comment](https://github.com/R4EPI/sitrep/issues/136#issuecomment-508481332) [comment 2](https://github.com/R4EPI/sitrep/issues/136#issuecomment-508494166) [comment 3](https://github.com/R4EPI/sitrep/issues/136#issuecomment-508754025)
This should also address [comment 4](https://github.com/R4EPI/sitrep/issues/136#issuecomment-508514444) and clarify what class variables need to be, e.g. sex as a factor (also add to notes?)
Cross reference with the [variable names & data dictionary]  point under training heading above.

**Comment by aspina7** [comment]
create functions to add sample size calculations see https://github.com/R4EPI/sitrep/issues/5

**Comment by aspina7** [comment]
Consider changing rmd outputs to those from [officer package](https://davidgohel.github.io/officer/) which allows us to put pagebreaks in (and generally gives more control of word doc outputs)

**Comment by aspina7** [comment]
on all plots - make y axis numbering go to top of axis, this happens because of expand(c(0,0)

**Comment by aspina7** [comment]
[see: https://github.com/reconhub/incidence/issues/105] on epicurves - possible to add a 2 weekly moving average? - issue posted on recon. Long term issue case.

**Comment by aspina7** [comment]
[Discussion] would be good to also output a document (beside the word) which summarises what datasets were used (and their file paths), starting cases, dropped cases where the output is. And maybe warnings/errors?

**Comment by zkamvar** [comment]
The one-big-issue-listing-a-whole-bunch-of-little-tasks is not really easy to reference when working on a specific task, so what I've done is made issues of each little task and am tracking them all in a github project, which makes it easier to track progress: https://github.com/R4EPI/sitrep/projects/1

I think we can keep this issue open as a discussion of these tasks.

**Comment by aspina7** [comment]
meeeennngg, y u no tell me about dis many moons ago?
