### ISSUE TITLE
msf_dict_rename_helper(): alphabetize and highlight which are OPTIONAL or NECESSARY

### ISSUE THREAD

**Issue by zkamvar** [R4EPI/sitrep#187]
[Sitrep - renaming vars] making non-DHIS datasets fit is very painful. Add explanation of sitrep::msf_dict_rename_helper()  - also add to this function to say whether those variables are OPTIONAL or NECESSARY for the template to run. Consider also changing variables to alphabetic order.
 
important comment: https://github.com/R4EPI/sitrep/issues/136#issuecomment-508481332

This should also address [comment 4](https://github.com/R4EPI/sitrep/issues/136#issuecomment-508514444) and clarify what class variables need to be, e.g. sex as a factor (also add to notes?)

Cross reference with the [variable names & data dictionary]  point under training heading above.

_Originally posted by @aspina7 in https://github.com/R4EPI/sitrep/issues/185#issuecomment-532647445_

**Comment by zkamvar** [comment]
I'm going  to work on this today. I'm almost there.

**Comment by aspina7** [comment]
i think you have finished this already dude

**Comment by zkamvar** [comment]
You are correct, this was fixed in #210
