### ISSUE TITLE
use officedown::rdocx instead of rmarkdown::word_document

### ISSUE THREAD

**Issue by zkamvar** [R4EPI/sitrep#188]
Consider changing rmd outputs to those from [officedown package](https://github.com/davidgohel/officedown) which allows us to put pagebreaks in (and generally gives more control of word doc outputs)

_Originally posted by @aspina7 in https://github.com/R4EPI/sitrep/issues/185#issuecomment-532648937_

ZNK note: This is an experimental package, so it's not necessarily wise to rely on it.

**Comment by aspina7** [comment]
Yeah - definitely not till its on cran

**Comment by aspina7** [comment]
is now on CRAN - worth considering, as could add a word template to {sitrep} and then we would be able to support page breaks and automated figure/table numbering

**Comment by aspina7** [comment]
no real point doing this anymore - should eventually switch everything to [quarto](https://quarto.org/)

**Comment by aspina7** [comment]
> no real point doing this anymore - should eventually switch everything to [quarto](https://quarto.org/)

closing because this
