### ISSUE TITLE
on all plots - make y axis numbering go to top of axis

### ISSUE THREAD

**Issue by zkamvar** [R4EPI/sitrep#189]
on all plots - make y axis numbering go to top of axis, this happens because of expand(c(0,0))

_Originally posted by @aspina7 in https://github.com/R4EPI/sitrep/issues/185#issuecomment-532649069_

**Comment by aspina7** [comment]
possible to do by setting scale_y_* (i think) to c(0,NA)

**Comment by aspina7** [comment]
https://github.com/ch-bu/ggplot2-fundamentals/blob/main/cheatsheets/08_ggplot2_fundamentals_cheatsheet_expansion_continuous.pdf
