### ISSUE TITLE
2-weekly moving average on epicurves

### ISSUE THREAD

**Issue by zkamvar** [R4EPI/sitrep#190]
[see: https://github.com/reconhub/incidence/issues/105] on epicurves - possible to add a 2 weekly moving average? - issue posted on recon. Long term issue case.

_Originally posted by @aspina7 in https://github.com/R4EPI/sitrep/issues/185#issuecomment-532649329_

**Comment by aspina7** [comment]
either wait for incidence2 or consider adding additional code using {slider} to then swap out at a later date

**Comment by aspina7** [comment]
done for all outbreak templates in #275
