### ISSUE TITLE
Create example code for maps

### ISSUE THREAD

**Issue by dirkschumacher** [R4EPI/sitrep#2]
- [ ] Pointmap shape file / geojson
- [ ] Pointmap dynamic base map
- [ ] Choropleth map  shape file / geojson
- [ ] Choropleth map dynamic base map

For the two types of maps I would like to have examples where the shapefile/geojson already exists (plus some code how to download a shapefile beforehand e.g. from HDX) and code that downloads the basemap from the internet using a tileprovider (e.g. ggmap).

**Comment by dirkschumacher** [comment]
Once #18 is merged, we can take the code and use it in the mortality survey if sensible.

**Comment by aspina7** [comment]
this has largely been addressed - i think a seperate walkthrough on interactive maps would be useful but doesnt fit within the template because outputting to word
