### ISSUE TITLE
Switch cowplot to patchwork

### ISSUE THREAD

**Issue by aspina7** [R4EPI/sitrep#217]
Patchwork has now been released on CRAN - might be nice to switch over?

**Comment by zkamvar** [comment]
I think it makes sense for what we want to do. I'll take a look at it this week. I know the map with the dynamite plot are fairly simple to do, the question is whether or not the weekly incidence curve will align properly

**Comment by zkamvar** [comment]
HOLY WOW IT WORKS PERFECTLY!
