### ISSUE TITLE
age pyramid package

### ISSUE THREAD

**Issue by zkamvar** [R4EPI/sitrep#219]
This also needs to take into account aggregate data (which we currently don't do).

There will be two functions:

1. `age_pyramid()`: takes in data and returns a plot
2. `aggregate_by_age()`: takes in linelist data and returns the aggregate in counts or proportions

My question is whether or not `age_pyramid()` should have a switch to indicate if the data are aggregated OR if we should build it so that we assume the data are aggregated. I'm leaning towards the other and we just import in sitrep and wrap it in plot_age_pyramid. 

 - [x] make package with two functions
 - [x] include srvyr as suggests? (if users want the srvyr functionality, they install it separately)
 - [ ] release to CRAN
 - [ ] import to sitrep

**Comment by aspina7** [comment]
think i lean towards the switch being wrapped in a single function?

**Comment by zkamvar** [comment]
The  problem with adding a switch is that it's more ways things can go wrong. In terms of current users from sitrep, this function would be wrapped inside `plot_age_pyramid()`, so they won't know the difference.

```r
plot_age_pyramid(x, ...) {
  x <- apyramid::aggregate_by_age(x, ...)
  apyramid::age_pyramid(x, ...)
}
```

**Comment by zkamvar** [comment]
aaaaand i just realized why forcing age_pyramid() to only take in aggregate data is not the best idea. It forces people to re-aggregate when they want to add a different stacking level and it looks messy:

```r
by_ill <- aggregate_by_age(x, AGE, stack_by = sex, split_by = ill)
by_casedef <- aggregate_by_age(x, AGE, stack_by = sex, split_by = casedef)

age_pyramid(by_ill, AGE, stack_by = sex, split_by = ill)
age_pyramid(by_casedef, AGE, stack_by = sex, split_by = casedef)
```

**Comment by aspina7** [comment]
hmmm does look a little messy...
