### ISSUE TITLE
Part of PBK review of mortality template part 2

### ISSUE THREAD

**Issue by pbkeating** [R4EPI/sitrep#222]
This is also in relation to the [mortality template](https://github.com/R4EPI/sitrep/tree/master/inst/rmarkdown/templates/mortality/skeleton)

line 1032: change in style and now directly starting with **group_by()** rather than the data frame  - I know it doesn't change anything but it may throw newbies if style changes a lot
https://github.com/R4EPI/sitrep/blob/9b44e408e70689a451d4062f109f6aefb670e7f2/inst/rmarkdown/templates/mortality/skeleton/skeleton.Rmd#L1032

line 1040: any reason this wasn't saved as an object? Just makes it easier to review the steps of the process
https://github.com/R4EPI/sitrep/blob/9b44e408e70689a451d4062f109f6aefb670e7f2/inst/rmarkdown/templates/mortality/skeleton/skeleton.Rmd#L1040

line 1053: what do we mean by many?
https://github.com/R4EPI/sitrep/blob/9b44e408e70689a451d4062f109f6aefb670e7f2/inst/rmarkdown/templates/mortality/skeleton/skeleton.Rmd#L1053

line 1096: why collapse == "--" instead of just "-"? Just so not interpreted as a minus?
https://github.com/R4EPI/sitrep/blob/9b44e408e70689a451d4062f109f6aefb670e7f2/inst/rmarkdown/templates/mortality/skeleton/skeleton.Rmd#L1096

- line 1131: just a minor fyi - due to random data dictionary generator, we get pregnant babies!
https://github.com/R4EPI/sitrep/blob/9b44e408e70689a451d4062f109f6aefb670e7f2/inst/rmarkdown/templates/mortality/skeleton/skeleton.Rmd#L1131

line 1245: the show_halfway is included by default, not sure it needs to be. Might be worth explaining this in comment, but yes, they can read the help file
https://github.com/R4EPI/sitrep/blob/9b44e408e70689a451d4062f109f6aefb670e7f2/inst/rmarkdown/templates/mortality/skeleton/skeleton.Rmd#L1245

- line 1331: may be worth naming the **ci** variable in output as **prop_ci**
https://github.com/R4EPI/sitrep/blob/9b44e408e70689a451d4062f109f6aefb670e7f2/inst/rmarkdown/templates/mortality/skeleton/skeleton.Rmd#L1331

- line 1468: any reason we don't just order based on the proportion?
https://github.com/R4EPI/sitrep/blob/9b44e408e70689a451d4062f109f6aefb670e7f2/inst/rmarkdown/templates/mortality/skeleton/skeleton.Rmd#L1468

line 1474: worth adding a line to fix the 95% CI, as negative with my dataset
https://github.com/R4EPI/sitrep/blob/9b44e408e70689a451d4062f109f6aefb670e7f2/inst/rmarkdown/templates/mortality/skeleton/skeleton.Rmd#L1474

line 1477: could consider ordering by proportion and fixing the 95% CI
https://github.com/R4EPI/sitrep/blob/9b44e408e70689a451d4062f109f6aefb670e7f2/inst/rmarkdown/templates/mortality/skeleton/skeleton.Rmd#L1477

line 1728: are these flow tables routinely presented in mortality surveys?
https://github.com/R4EPI/sitrep/blob/9b44e408e70689a451d4062f109f6aefb670e7f2/inst/rmarkdown/templates/mortality/skeleton/skeleton.Rmd#L1728

**Comment by zkamvar** [comment]
Hi pat, I think it's better to keep the review in one place as opposed to splitting it up in multiple issues. I'm going to close this and copy your comments over to #221
