### ISSUE TITLE
basic univariate analysis package

### ISSUE THREAD

**Issue by zkamvar** [R4EPI/sitrep#229]
This should encompass the following functions:

 - `tab_univariate()` 
 - `data_frame_from_2x2()`
 
I will also need to add more tests and address the issue where it currently only accepts TRUE/FALSE for strata variables, when strata could be any binary variable. I should also make it so that it can accept 1/0 data (as is not uncommon)

**Comment by zkamvar** [comment]
This is currently codename tuni: https://github.com/R4EPI/tuni

**Comment by aspina7** [comment]
>  I should also make it so that it can accept 1/0 data (as is not uncommon)

Maybe a general purpose switcher func in the background? That accepts any vars which are TRUE/FALSE, Yes/No, Y/N, 1/0 or two leveled categorical at which point it returns which level used as TRUE and FALSE

**Comment by zkamvar** [comment]
> Maybe a general purpose switcher func in the background? That accepts any vars which are TRUE/FALSE, Yes/No, Y/N, 1/0 or two leveled categorical at which point it returns which level used as TRUE and FALSE

I think I can do that. It will definitely fail if you ever get any french responses, but we can provide instructions down the road.

In the future, it might be a good idea to allow users to specify their own expressions that return TRUE/FALSE. 

```r
tab_univariate(x, outcome = ill == "yes", 
  meal == "fish", 
  drink == "water", 
  strata = gender
)
```

The only potential issue from that would be the fact that the rows of the table would be named like `meal == "salmon"` or `str_detect("Yes", previously_vaccinated)`

**Comment by aspina7** [comment]
hmmm not a bad idea, but might get annoying to type out? 
particularly if just want to chuck a bunch of vars in.... 

maybe make it like tab_linelist where output has variable column and value column?

**Comment by zkamvar** [comment]
> hmmm not a bad idea, but might get annoying to type out?
> particularly if just want to chuck a bunch of vars in....

If you want to chuck a bunch of vars it, it will work as it currently does if they are all logical vars

> maybe make it like tab_linelist where output has variable column and value column?

This wouldn't make sense for multiple conditions or fuzzy matching.

**Comment by zkamvar** [comment]
Update: this package has been merged with the idea for a generic table package (https://github.com/R4EPI/sitrep/projects/2#card-27006876) and is now at

https://github.com/R4EPI/epibuffet

Some like the name, some hate the name, but that's the way it is.

**Comment by aspina7** [comment]
soooooo the {epitable} package has been archived on cran - does that mean we could use name?

**Comment by zkamvar** [comment]
> soooooo the {epitable} package has been archived on cran - does that mean we could use name?

Nope. All names used in the past are taken.

**Comment by aspina7** [comment]
> > soooooo the {epitable} package has been archived on cran - does that mean we could use name?
> 
> Nope. All names used in the past are taken. I know... I'm not terribly happy about it as well.

ah poo
