### ISSUE TITLE
Field-ready mortality survey

### ISSUE THREAD

**Issue by dirkschumacher** [R4EPI/sitrep#23]
The current mortality survey template has three sample analysis chunks. This needs to be extended, probably, in order to make it field ready. In particular more code comments need to be included.

In a similiar fashion to what @aspina7 is doing for the outbreak templates in #18.

**Comment by lukric** [comment]
Hey guys, just to let you know, I started to work on the mortality survey.

I will remove the sample size calculations as sugested by @dirkschumacher in #63
