### ISSUE TITLE
PBK review of the AJS template

### ISSUE THREAD

**Issue by pbkeating** [R4EPI/sitrep#232]
This review relates to this [template](https://github.com/R4EPI/sitrep/blob/master/inst/rmarkdown/templates/ajs_outbreak/skeleton/skeleton.Rmd)

- [x] Add dfSummary
https://github.com/R4EPI/sitrep/blob/50c3b792b052c52f3d0d111c4f9d36ed5b75b320/inst/rmarkdown/templates/ajs_outbreak/skeleton/skeleton.Rmd#L497
**Alex**: depend on prev decision. 

- [x] code styling
https://github.com/R4EPI/sitrep/blob/50c3b792b052c52f3d0d111c4f9d36ed5b75b320/inst/rmarkdown/templates/ajs_outbreak/skeleton/skeleton.Rmd#L591
**Alex**: will update. 

- [x] code styling
https://github.com/R4EPI/sitrep/blob/50c3b792b052c52f3d0d111c4f9d36ed5b75b320/inst/rmarkdown/templates/ajs_outbreak/skeleton/skeleton.Rmd#L741-L743
**Alex**: will update. 

- [x] Add these explanations for tab_linelist to all the other templates
https://github.com/R4EPI/sitrep/blob/50c3b792b052c52f3d0d111c4f9d36ed5b75b320/inst/rmarkdown/templates/ajs_outbreak/skeleton/skeleton.Rmd#L1007-L1026
**Alex**: the first occurance in each template is this i believe. 

- [x]  Case fatality rate instead of case fatality ratio - needs to be replaced elsewhere in the Rmd
https://github.com/R4EPI/sitrep/blob/50c3b792b052c52f3d0d111c4f9d36ed5b75b320/inst/rmarkdown/templates/ajs_outbreak/skeleton/skeleton.Rmd#L1131
**Alex**: kostas would be so disappointed in you assoc prof of data science.

- [x]  Could add "Check ?complete for more info" or state that "Complete will add zeros (in this cases) for all variables specified where there are missing values"
https://github.com/R4EPI/sitrep/blob/50c3b792b052c52f3d0d111c4f9d36ed5b75b320/inst/rmarkdown/templates/ajs_outbreak/skeleton/skeleton.Rmd#L1215-L1219
**Alex**: will add the comment as prev. 

- [x] Important to add names of cases to the epicurves, as the same report may include ajs, measles, cholera and just easier for the person preparing
https://github.com/R4EPI/sitrep/blob/50c3b792b052c52f3d0d111c4f9d36ed5b75b320/inst/rmarkdown/templates/ajs_outbreak/skeleton/skeleton.Rmd#L1475
**Alex**: that is for individuals to edit. 

- [x] Again, could to explain what "e=" means
https://github.com/R4EPI/sitrep/blob/50c3b792b052c52f3d0d111c4f9d36ed5b75b320/inst/rmarkdown/templates/ajs_outbreak/skeleton/skeleton.Rmd#L1685-L1692
**Alex**: as previous decision. 

- [x] Need to add in rename("Week" = value)
https://github.com/R4EPI/sitrep/blob/50c3b792b052c52f3d0d111c4f9d36ed5b75b320/inst/rmarkdown/templates/ajs_outbreak/skeleton/skeleton.Rmd#L1796-L1804
**Alex**: will add.

**Comment by pbkeating** [comment]
@aspina7 

See from this line on where the AR per 10000 is calculated rather than %
I think it's the same for all the others.

https://github.com/R4EPI/sitrep/blob/74088bd06bcd68f7f72aad552426b8cff14385fc/inst/rmarkdown/templates/ajs_outbreak/skeleton/skeleton.Rmd#L1256

**Comment by pbkeating** [comment]
> @aspina7
> 
> See from this line on where the AR per 10000 is calculated rather than %
> I think it's the same for all the others.
> 
> https://github.com/R4EPI/sitrep/blob/74088bd06bcd68f7f72aad552426b8cff14385fc/inst/rmarkdown/templates/ajs_outbreak/skeleton/skeleton.Rmd#L1256

And then I look at the DRC seroprevalence paper and see that we reported attack rates as 

Additionally, they had been variably affected by the 2010–2013 and 2015 epidemics (Fig. 1), with attack rates (AR) during the latter in children under 5 of 132.0 cases/100000

**Comment by aspina7** [comment]
> @aspina7
> 
> See from this line on where the AR per 10000 is calculated rather than %
> I think it's the same for all the others.
> 
> https://github.com/R4EPI/sitrep/blob/74088bd06bcd68f7f72aad552426b8cff14385fc/inst/rmarkdown/templates/ajs_outbreak/skeleton/skeleton.Rmd#L1256

leaving as per 10,000 as we will have situations where denom less than 100.
