### ISSUE TITLE
First draft nutrition survey

### ISSUE THREAD

**Issue by dirkschumacher** [R4EPI/sitrep#24]
We need a first draft for a nutrition survey:

The package `anthro` provides most of the necessary z-score calculations and is a good contender to be used here. However it seems that prevalence calculation has slightly different rules compared to the ones implemented in the package.

**Comment by zkamvar** [comment]
I can't seem to find the anthro package. Where does it live?

**Comment by dirkschumacher** [comment]
For the record: the z-score calculation is not terribly complicated, so we could also replicate it here as a fallback.

**Comment by aspina7** [comment]
getting there - closing for now
