### ISSUE TITLE
Not available in CRAN

### ISSUE THREAD

**Issue by psubias** [R4EPI/sitrep#241]
The main README.md file says that the package can be downloaded from CRAN. However, by one of the tags of the project, you indicate that the package can not be downloaded from CRAN yet. I have checked in the CRAN repository and, indeed, the package is not published there. Could you fix the inconsistency?

Thanks!

**Comment by psubias** [comment]
I think that adding the information about installing "sitrep" that is already available in https://r4epis.netlify.com/welcome/#installing-the-sitrep-package will be of great help!

**Comment by zkamvar** [comment]
Hello @psubias, can you check that these instructions work for you? https://github.com/R4EPI/sitrep/tree/581143708545e75b908f87c0e4b7a8756d01ffc5#readme

**Comment by psubias** [comment]
Yes, it is! Good work.
