### ISSUE TITLE
Default code for some measles template epicurves does not allow visualisation of grouped variable

### ISSUE THREAD

**Issue by pbkeating** [R4EPI/sitrep#246]
Ran code for epicurve by vaccination status and was not able to see the epicurve filled in by the values of the vaccination variable. This is because show_cases = TRUE and needs to be FALSE

Example below, but not the only one.  Haven't checked the other templates if it is the same.

https://github.com/R4EPI/sitrep/blob/3f2cbd113b0a43f62fbe468e2ed9c765a52b18b1/inst/rmarkdown/templates/measles_outbreak/skeleton/skeleton.Rmd#L1618

**Comment by aspina7** [comment]
so we want to have show_cases as FALSE everywhere? or only for grouped?

**Comment by aspina7** [comment]
@pbkeating still dont know what this is supposed to mean?

**Comment by aspina7** [comment]
set all to FALSE in all outbreak templates

**Comment by pbkeating** [comment]
Reviewing this and it doesn't seem to cause any problem with the template. Not sure if it was something related to the dataset we had for CAR, but think it can stay as it is.
