### ISSUE TITLE
Update dataset from raw to cleaned in browse_data chunk of VCS template

### ISSUE THREAD

**Issue by pbkeating** [R4EPI/sitrep#253]
In line 254 of the Measles VCS template, we create study_data_cleaned but then in lines 403 onwards, we browse the  study_data_raw, which doesn't make much sense

https://github.com/R4EPI/sitrep/blob/3f2cbd113b0a43f62fbe468e2ed9c765a52b18b1/inst/rmarkdown/templates/vaccination/skeleton/skeleton.Rmd#L254

https://github.com/R4EPI/sitrep/blob/3f2cbd113b0a43f62fbe468e2ed9c765a52b18b1/inst/rmarkdown/templates/vaccination/skeleton/skeleton.Rmd#L405

**Comment by aspina7** [comment]
same same data set - but really you should be browsing the raw as thats where the errors are. (in this case clean is still raw at this point ... but out of principle...)
