### ISSUE TITLE
Update the export of VCS cleaned data to the data folder

### ISSUE THREAD

**Issue by pbkeating** [R4EPI/sitrep#255]
Upon knitting the Rmd, the export of the cleaned data currently saves the cleaned data in the same folder as the code.
Possible to update so that it exports to the data folder?

https://github.com/R4EPI/sitrep/blob/3f2cbd113b0a43f62fbe468e2ed9c765a52b18b1/inst/rmarkdown/templates/vaccination/skeleton/skeleton.Rmd#L811-L813

`rio::export(study_data_cleaned, 
            file = here::here("9_data", "clean", str_glue("study_data_cleaned_{Sys.Date()}.xlsx")))`

**Comment by aspina7** [comment]
actually this will apply throughout

**Comment by aspina7** [comment]
updated all paths for outbreaks to point to "Data" folder - you will likely need to update this once sharepoint folder structure is finalised.
