### ISSUE TITLE
Swapping tab_* for {gtsummary}

### ISSUE THREAD

**Issue by aspina7** [R4EPI/sitrep#260]
May be worth considering to use {[gtsummary ](http://www.danieldsjoberg.com/gtsummary/)} for descriptive tables. 

Would mean swapping to {[flextable ](https://davidgohel.github.io/flextable/)} rather than kable. Which would also play nicely if we swapped to officedown as in #188 

Would then mean that we could retire tab_linelist and would significantly lighten {[epibuffet](https://github.com/R4EPI/epibuffet)}. 

Thoughts @zkamvar @pbkeating ?

**Comment by zkamvar** [comment]
I fully support this idea. I don't know if it would necessarily lighten epibuffet since much of the weight is coming from {surveyr}, but I like the approach of {gt} and {gtsummary} and think that it has had a lot more thought an effort put into it than {epibuffet}.

**Comment by aspina7** [comment]
also has functions for [survey weighted tables ](http://www.danieldsjoberg.com/gtsummary/articles/tbl_summary.html#tbl_svysummary) 
as well as for [inline text](http://www.danieldsjoberg.com/gtsummary/articles/inline_text.html)

**Comment by zkamvar** [comment]
I am 100% for this (assuming it works for our use-cases). We may even consider just making {gtsummary} a backend for {epibuffet}

**Comment by aspina7** [comment]
turns out is possible to replicate the results of our tab_univariate (example below) - so actually the only wrapper that needs writing is to produce stratified estimates (mantel haenszel) 
@pbkeating this shaves off a bit of time! 

```r
output <- linelist %>% 
  select(died_covid, gender, age_group) %>%    # keep variables of interest
  tbl_uvregression(                         ## produce univariate table
    method = glm,                           ## define regression want to run (generalised linear model)
    y = died_covid,                            ## define outcome variable
    method.args = list(family = binomial),  ## define what type of glm want to run (logistic)
    exponentiate = TRUE,                    ## exponentiate to produce odds ratios (rather than log odds)
    hide_n = TRUE                               ## dont include overall counts in regression table
  ) 

## produce counts for each of the variables of interest
cross_tab <- output$inputs$data %>% 
  tbl_summary(by = died_covid)

## combine for a full table 
tbl_merge(list(cross_tab, output))
```

**Comment by aspina7** [comment]
in progress for surveys in #275
