### ISSUE TITLE
update website install instructions

### ISSUE THREAD

**Issue by aspina7** [R4EPI/sitrep#264]
have added summarytools to suggests so need to update install instructions where appropriate to also install dependencies 
as discussed in #223

**Comment by pbkeating** [comment]
Have added ,dep = TRUE for sitrep installation on the website.
Is that the only thing that needed to be done?

**Comment by aspina7** [comment]
I believe so,.... Think I added summarytools to suggests in the description
file. But not at comp so can't double check.
