### ISSUE TITLE
swap {epitrix} and {linelist} for {janitor} 

### ISSUE THREAD

**Issue by aspina7** [R4EPI/sitrep#267]
The {[janitor](http://sfirke.github.io/janitor/articles/janitor.html)} package has functions for cleaning names, dealing with messy dates and flagging duplicate rows. 
Not sure if worth swapping all out to consistently use janitor - or if is a dependency issue? 
Placing this under nice-to-haves for pat to deal with if decides should be done. 
@zkamvar thoughts? (reposting on github rather than email for posterity)

**Comment by zkamvar** [comment]
I think it may be worthwhile, especially since I don't think {epitrix} will be updated any time soon. It appears that {janitor} has undergone some major improvements and may help address the issues we found with substituting the ">" and "<" symbols.

**Comment by aspina7** [comment]
keeping {linelist} for guessdates but swapping {epitrix} for {janitor}

**Comment by aspina7** [comment]
Could probably swap linelist::guess_dates for {anytime}
http://dirk.eddelbuettel.com/code/anytime.html

**Comment by aspina7** [comment]
swapping {linelist} for {parsedate} re zhians post above
