### ISSUE TITLE
Warning message when using tab_survey in the VCS template

### ISSUE THREAD

**Issue by pbkeating** [R4EPI/sitrep#268]
Unclear of what the consequences are of the following message when using tab_survey() for example in the Bossangoa VCS based off the VCS template

![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/20238915/90406642-25b87b80-e0ae-11ea-899b-d6fd9ad050b8.png)

**Comment by aspina7** [comment]
This is fine but just means that confidence intervals will be a bit less accurate than otherwise. @zkamvar am not sure where this would go but could you maybe replace this warning with something more helpful, i.e. "warning: for variable x, estimates and confidence intervals may be less reliable (glm regression did not converge)".

**Comment by zkamvar** [comment]
It IS possible to capture these and I think they would go into {epibuffet}, which will hopefully be fixed once we address #234 One of the problems is that I'm not sure how to set up data that would replicate that warning for testing :(

**Comment by zkamvar** [comment]
In FACT, I think we can add a warning catch in here that would grab that warning and explain it.

https://github.com/R4EPI/epibuffet/blob/56998b606f2863f0b2f8dcc6b62265ff9ad4cace/R/tabulate_survey.R#L141-L166

**Comment by zkamvar** [comment]
I've added it into {epibuffet}, but don't have a test for it, so I hope that things work out 🤞

**Comment by aspina7** [comment]
awesome stuff zhian - have added a nice to have for the tests, i think i might be able to work this out but need to think about it.... will do eventually but for now lets just be happy we have this :)

**Comment by aspina7** [comment]
closing this as there is a separate issue for adding tests
