### ISSUE TITLE
kobo mortality dict doesnt have morbidity

### ISSUE THREAD

**Issue by aspina7** [R4EPI/sitrep#276]
The current Kobo dictionaries for mortality surveys does not include any questions on morbidity - previously there were questions on whether people had been sick in the previous 2 weeks. 

On purpose? or just missed?

**Comment by aspina7** [comment]
also - i havent added extra tables for violence or education.

**Comment by pbkeating** [comment]
The standard questionnaire doesn't have any question on people being sick in the previous two weeks. That's what we used to make the excel template.

**Comment by pbkeating** [comment]
So...thanks to your comment, I discovered that there are multiple modules associated with the pre-approved mortality survey. The one that Raphael and I made for KoBo only covers the most basic mortality survey (I've never done one). So, we will have to add the other modules to this template before this part can be finalised. Not sure when that will be though just yet.

**Comment by aspina7** [comment]
completed in https://github.com/R4EPI/epidict/pull/20
