### ISSUE TITLE
CMR month chunk produces unrealistic CMR values compared to the overall summary CMR

### ISSUE THREAD

**Issue by pbkeating** [R4EPI/sitrep#283]
@aspina7 When running the CMR_months chunk in the mortality survey template the monthly CMR values obtained are unrealistically high e.g. get an overall CMR of 0.1 but have values of 13, 23, 65, 218 per month. I think there is an issue with the calculation of obstime here per month?

**Comment by aspina7** [comment]
i dont see why that would happen - can share example data?

**Comment by aspina7** [comment]
So the reason this is happening is that currently the obs are for the whole period - so we need to write a loop to calculate obstime for each month for each person and then calculate deaths/month_obs to get appropriate estimates....
