### ISSUE TITLE
Use rio as default data import package

### ISSUE THREAD

**Issue by zkamvar** [R4EPI/sitrep#30]
@epiamsterdam has pointed out that [the rio package](https://cloud.r-project.org/web/packages/rio/vignettes/rio.html#supported_file_formats) has a simple interface of `import()` and `export()` and has sensible defaults for guessing the file format. This would be extremely useful for epis who just need to get their data into R. The only downside is that it will introduce a lot of hidden layers of dependencies.

**Comment by aspina7** [comment]
This has been implemented
