### ISSUE TITLE
Include rmapshaper and lwgeom packages in Suggests

### ISSUE THREAD

**Issue by zkamvar** [R4EPI/sitrep#34]
This stems from the fact that the function [`tmaptools::simplify_shape()`](https://github.com/mtennekes/tmaptools/blob/25df2ee5e847a831a45a154e2744b61e20383f30/R/simplify_shape.R) uses *suggested* packages, so they are missed on installation as R doesn't install suggests of dependent packages. 

The only issue is that rmapshaper needs rJava to work, which will be problematic on Linux systems (hi @thibautjombart :wave:) unless the correct incantations are used to configure it correctly.

**Comment by zkamvar** [comment]
Update: rmapshaper and OpenStreetMap both depend on rJava, which does not appear to work out of the box on Linux of Mac. Can someone see if they work on windows?

**Comment by aspina7** [comment]
worked for me - though im pretty convinced we should use ggspatial, lets see what chris comes back with

**Comment by aspina7** [comment]
We are no longer using tmaptools - switched to sf with ggspatial, therefor this no longer an issue
