### ISSUE TITLE
Improve age pyramid

### ISSUE THREAD

**Issue by dirkschumacher** [R4EPI/sitrep#4]
Not sure if ggpyramid of reconhub should be used or we improve the code within this package.

**Comment by aspina7** [comment]
So dplyr apparently doesnt include factor levels with zero counts, must be some workaround but a quick google got me no-where. So say you have an over 80 age group and theres none in there - plot_age_pyramid will just show the group below that max age.

**Comment by dirkschumacher** [comment]
Ok. Just a assume the code works perfectly in the template. I can improve it :)

**Comment by aspina7** [comment]
Age pyramid works well - the issue of not including NA groups still there though (see two comments above). May also be good to include an option to change text size? @zkamvar

**Comment by dirkschumacher** [comment]
The age pyramid code needs to be extended such that you can choose arbitrary groups for coloring. Currently it is by sex, but I have also seen by case definition

**Comment by dirkschumacher** [comment]
@zkamvar is this something you can take a look at?

**Comment by zkamvar** [comment]
ja!

**Comment by zkamvar** [comment]
> Age pyramid works well - the issue of not including NA groups still there though (see two comments above). May also be good to include an option to change text size? @zkamvar

I was able to get the NA groups to show up, though. Is it desireable to get something else?

``` r
library("epireports")
set.seed(2018-01-15)
ages <- cut(sample(80, 150, replace = TRUE),
            breaks = c(0, 5, 10, 30, 70), right = FALSE)
sex  <- sample(c("Female", "Male"), 150, replace = TRUE)
ill  <- sample(0:1, 150, replace = TRUE)
dat  <- data.frame(AGE = ages, sex = sex, ill = ill, stringsAsFactors = FALSE)
print(ap   <- plot_age_pyramid(dat, age_group = "AGE"))
```

![](https://i.imgur.com/Q3ldSZs.png)

``` r
print(ap   <- plot_age_pyramid(dat, age_group = "AGE", split_by = "ill"))
```

![](https://i.imgur.com/UVsJnEu.png)

<sup>Created on 2019-01-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by aspina7** [comment]
ah nice! 
And what if there is a factor level with zero counts? Cus I couldnt get that to work either....

**Comment by zkamvar** [comment]
Ah! Still can't do that, but I'll see if I can give it a go

**Comment by zkamvar** [comment]
BLAM! 

``` r
library("epireports")
set.seed(2018-01-15)
ages <- cut(sample(80, 150, replace = TRUE),
           breaks = c(0, 5, 10, 30, 50, 80, 100), right = FALSE)
sex  <- sample(c("Female", "Male"), 150, replace = TRUE)
ill  <- sample(0:1, 150, replace = TRUE)
dat  <- data.frame(AGE = ages, sex = sex, ill = ill, stringsAsFactors = FALSE)
datd <- dat[dat$AGE != levels(dat$AGE)[2], , drop = FALSE]
print(ap3 <- plot_age_pyramid(datd, age_group = "AGE"))
#> Warning: Removed 1 rows containing missing values (position_stack).
```

![](https://i.imgur.com/mKpuMQa.png)

``` r
ap3$data
#> # A tibble: 10 x 4
#> # Groups:   AGE [6]
#>    AGE      sex        n .group
#>    <fct>    <chr>  <int>  <int>
#>  1 [0,5)    Female    -3      1
#>  2 [0,5)    Male       3      1
#>  3 [5,10)   <NA>      NA      2
#>  4 [10,30)  Female   -22      3
#>  5 [10,30)  Male      27      3
#>  6 [30,50)  Female   -16      4
#>  7 [30,50)  Male      19      4
#>  8 [50,80)  Female   -24      5
#>  9 [50,80)  Male      25      5
#> 10 [80,100) Female    -4      6
```

<sup>Created on 2019-01-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by dirkschumacher** [comment]
Looks like it is good for now?

**Comment by aspina7** [comment]
Yep perfect! 
Will eventually tinker with some aesthetic stuff like being able to not show the y-axis line. Showing horizontal dashed lines at each group and being able to mess with text size. 
But for now is great as is

**Comment by dirkschumacher** [comment]
I will close it. Feel free to open a new issue for specific things
