### ISSUE TITLE
Question: who is the copyright holder?

### ISSUE THREAD

**Issue by zkamvar** [R4EPI/sitrep#44]

**Comment by dirkschumacher** [comment]
@epiamsterdam?

**Comment by dirkschumacher** [comment]
I assume MIT is still fine though? also @thibautjombart @AmmerB

**Comment by AmmerB** [comment]
If possible I would add all the authors on the abstract that we submitted :) Alphabetical order might be easiest, although for technical purposes easier to add the core team of people who contributed to the tech side of the package.

**Comment by epiamsterdam** [comment]
Copyright holder to all the script? Isnt the whole point that there is NO copyright?
If you need to attribute credit, then I would include everyone that has contributed to the existing code in some meaningful way.

**Comment by dirkschumacher** [comment]
The whole business of copyright comes in addition to a license. So you can have an open license but still have a copyright holder. You can transfer everything into the public domain, but even that is not accepted in all jurisdictions. But I am not a lawyer.

Having said that, why not write in the `LICENSE` file "Copyright holder: the contributors". I think I have seen this in other projects

**Comment by epiamsterdam** [comment]
OK. I am checking with the Sapling Nursery coordinator what the rules are around this and will get back toyou!

**Comment by AmmerB** [comment]
Based on the feedback of @epiamsterdam, copyright holders should be core contributors including one or two persons from MSF e.g. @epiamsterdam. That makes sense to me.

**Comment by aspina7** [comment]
resurecting this discusison here https://github.com/R4EPI/sitrep/issues/146#issue-469140947

**Comment by dirkschumacher** [comment]
Some projects have "The contributors" or a similar formulation as copyright holders.
