### ISSUE TITLE
change default output for templates to html_document?

### ISSUE THREAD

**Issue by dirkschumacher** [R4EPI/sitrep#49]
Currently it is `github_document`. I think `html_document` is a sensible default. Change my mind.

**Comment by zkamvar** [comment]
+1

**Comment by aspina7** [comment]
Longterm it needs to be word documents! Or atleast the option to do so...  Because msf epis have to integrate their section in to larger sitreps for the whole mission.

**Comment by dirkschumacher** [comment]
Then let’s make it word.

**Comment by zkamvar** [comment]
Word.
