### ISSUE TITLE
Support sample size calculations for all three surveys

### ISSUE THREAD

**Issue by dirkschumacher** [R4EPI/sitrep#5]
For now, the method of openEpi is implemented, but more code might be needed:

- [ ] Finish, test and document the current functions
- [ ] Decide if more methods are needed
- [ ] Include code in all three report types

**Comment by dirkschumacher** [comment]
There is some basic code in the package already. It is based on the openEpi Website. However it seems, there are slightly different interfaces to the same problem.

**Comment by dirkschumacher** [comment]
Not in the scope of this round anymore. See #63

**Comment by aspina7** [comment]
note to self: check out https://github.com/mbaldassaro/sampler
