### ISSUE TITLE
Add more authors to the package

### ISSUE THREAD

**Issue by dirkschumacher** [R4EPI/sitrep#51]
@zkamvar @aspina7 please add yourself as authors to the packages.

Also I think it might make sense to add all other project folks as `ctb`. Or shall we leave the `DESCRIPTION` file for code contributions only?

**Comment by dirkschumacher** [comment]
But #44 needs to be resolved first

**Comment by zkamvar** [comment]
IMO, all contributions should be acknowledged. There might be a reviewer role that we can attach.

**Comment by dirkschumacher** [comment]
Ok sounds very well to me. I think we should make a suggestions with appropriate roles and then ask folks if they want to be named.

**Comment by AmmerB** [comment]
Potentially good to start off with the names from the abstracts we submitted for the Sci days.

**Comment by aspina7** [comment]
implemented in https://github.com/R4EPI/sitrep/pull/138
