### ISSUE TITLE
Nice output for 2x2 tables

### ISSUE THREAD

**Issue by dirkschumacher** [R4EPI/sitrep#6]
Currenlty we use `epitools`, but we might want to add functions that improve the output of these tests.

See previous discussions here:
https://github.com/R4EPI/outbreaks/issues/6
https://github.com/R4EPI/projmgmt/issues/1

**Comment by aspina7** [comment]
This is done. See [discussion on univariate](https://github.com/R4EPI/epireports/issues/8#issuecomment-453069394). 
Also added the descriptive table function.
