### ISSUE TITLE
Create an R4EPI drat repository 

### ISSUE THREAD

**Issue by zkamvar** [R4EPI/sitrep#68]
This is related to the multiple issues seen in #55, @dirkschumacher has suggested creating a drat repository so users don't have to rely on building the binary packages themselves (https://github.com/R4EPI/sitrep/issues/55#issuecomment-460043808).

**Comment by zkamvar** [comment]
Point: This can have appveyor integration to be able to build windows versions.

**Comment by aspina7** [comment]
closing as moving to r-universe and cran
