### ISSUE TITLE
univariate analyses

### ISSUE THREAD

**Issue by dirkschumacher** [R4EPI/sitrep#8]
@aspina7 looked at what Dan did and coded a quick prototype for RR based on his output format. Does this go in the right direction?
https://github.com/R4EPI/outbreaks/blob/master/oubreak-report.md

**Comment by aspina7** [comment]
Have done the basics of this too - perhaps a next step would be to look at stratified options producing maentel-haszel estimates. Though I would be more comfortable moving that to regression rather than messing around with a third dimension table...
